"""Claim authority carried with every V7 scientific result."""

from enum import StrEnum


class ClaimAuthority(StrEnum):
    SYNTHETIC_MECHANISM = "SYNTHETIC_MECHANISM"
    SYNTHETIC_ECONOMIC = "SYNTHETIC_ECONOMIC"
    REAL_RANDOMIZED_PROXY_OUTCOME = "REAL_RANDOMIZED_PROXY_OUTCOME"
    REAL_RANDOMIZED_REVENUE = "REAL_RANDOMIZED_REVENUE"
    REAL_RANDOMIZED_CONTRIBUTION_PROFIT = "REAL_RANDOMIZED_CONTRIBUTION_PROFIT"
    OBSERVATIONAL_ASSOCIATION = "OBSERVATIONAL_ASSOCIATION"
    INSUFFICIENT = "INSUFFICIENT"

    @property
    def permits_real_merchant_profit_claim(self) -> bool:
        return self is ClaimAuthority.REAL_RANDOMIZED_CONTRIBUTION_PROFIT
